config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
	scope "(:locale)", :locale => /en|de/ do
		root  'pages#index'
		get   'favicon',    to: 'pages#favicon'
		match 'container_definition', to: 'pages#container_definition', via: 'get'
		match 'init_create',          to: 'inits#create',               via: 'post', as: 'init_create_submit'
		match 'usage_create',         to: 'usages#create',              via: 'post', as: 'usage_create_submit'
		match 'usage_match',          to: 'usages#match',               via: 'post', as: 'usage_match_submit'
		match 'data_validate',        to: 'data_formats#validate',      via: 'post', as: 'data_validate_submit'
		match 'usage_policy',         to: 'pages#usage_policy',         via: 'get'
		match 'data_format',          to: 'pages#data_format',          via: 'get'
		match 'provenance',           to: 'pages#provenance',           via: 'get'
	end
end

app/views/pages/_data_validate.html.erb
<%= form_with url: data_validate_submit_path do |form| %>
    <%= form.hidden_field :sidebar, value: params[:sidebar] %>
    <%= form.hidden_field :mode, value: "validate" %>
    <h4><%= t('data.input_data') %></h4>
    <p style><%= t('data.input_data_text') %></p>
    <%= form.hidden_field :input_data, id: "input_data" %>
    <div id="editor_input_data" style="height: 100px; width: 100%; border-radius: 2px; border: 1px solid #DDD; margin-bottom: 15px;"><%= @data_format_input_data %></div>
    <p>&nbsp;</p>

    <h4><%= t('data.constraints') %></h4>
    <p><a href="https://en.wikipedia.org/wiki/SHACL">SHACL</a> <%= t('data.constraints_text') %></p>
    <%= form.hidden_field :data_constraints, id: "data_constraints" %>
    <div id="editor_data_constraints" style="height: 100px; width: 100%; border-radius: 2px; border: 1px solid #DDD; margin-bottom: 15px;"><%= @data_format_constraints %></div>

    <% if !@data_valid.nil? 
            if @data_valid %>
                <div class="alert alert-success">
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                    <%= t('data.validation_success') %>
                </div>
         <% else %>
                <div class="alert alert-danger">
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                    <%= t('data.validation_failure') %>
                </div>
         <% end
       end %>

    <%= form.button value: "validate", class: "btn btn-primary", style:"margin-right: 10px;", onclick: "$('#input_data').val(ace.edit('editor_input_data').getSession().getValue()); $('#data_constraints').val(ace.edit('editor_data_constraints').getSession().getValue()); return true;" do %>
        <span class="fa fa-check-square-o" aria-hidden="true"></span>
        <%= t('data.validate') %>
    <% end %>
    <%= form.button value: "reset", class: "btn btn-default" do %>
        <span class="glyphicon glyphicon-refresh" aria-hidden="true"></span>
        <%= t('general.reset') %>
    <% end %>
<% end %>

<script type="text/javascript">
    var editor_input_data = ace.edit("editor_input_data");
    editor_input_data.setOptions({
        showPrintMargin: true,
        maxLines: 10,
        fontSize: "100%"
    });
    editor_input_data.setTheme("ace/theme/chrome");
    editor_input_data.renderer.setOption("showLineNumbers", true);

    var editor_data_constraints = ace.edit("editor_data_constraints");
    editor_data_constraints.setOptions({
        showPrintMargin: true,
        maxLines: 10,
        fontSize: "100%"
    });
    editor_data_constraints.setTheme("ace/theme/chrome");
    editor_data_constraints.renderer.setOption("showLineNumbers", true);
</script>

app/views/pages/_init_create.html.erb
<%= form_with url: init_create_submit_path do |form| %>
    <%= form.hidden_field :sidebar, value: params[:sidebar] %>
    <h4><%= t('general.settings') %></h4>
    <div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
        <div class="panel panel-default">
            <div class="panel-heading" role="tab" id="headingOne">
              <h4 class="panel-title">
                <a role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseOne" aria-expanded="false" aria-controls="collapseOne">
                  <%= t('general.init.general') %>
                </a>
              </h4>
            </div>
            <div id="collapseOne" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingOne">
                <div class="panel-body">
                    <div class="row">
                        <div class="form-group">
                            <label class="col-xs-3 col-md-2 control-label" style="margin-top: 14px;"><%= t('general.init.title') %>:</label>
                            <div class="col-xs-9 col-md-10" style="margin-top: 7px;">
                                <%= form.text_field :title, value: @title %>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="form-group">
                            <label class="col-xs-3 col-md-2 control-label" style="margin-top: 14px;"><%= t('general.init.description') %>:</label>
                            <div class="col-xs-9 col-md-10" style="margin-top: 7px;">
                                <%= form.text_area :description, rows: 2, style: "width: 100%", value: @description %>
                            </div>
                        </div>
                    </div>
                    <div class="row" style="margin-bottom: 5px;">
                        <div class="form-group">
                            <label class="col-xs-3 col-md-2 control-label" style="margin-top: 14px;"><%= t('general.init.creator') %>:</label>
                            <div class="col-xs-9 col-md-10" style="margin-top: 7px;">
                                <%= form.collection_select(:creator_type,
                                        { t('general.init.creator_none')       => "none",
                                          t('general.init.creator_type_person')       => "person",
                                          t('general.init.creator_type_organization') => "org" }, 
                                        :last, :first, { selected: @creator_type }, 
                                        multiple: false, id: "creator_type-selection" ) %>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="form-group">
                            <label class="col-xs-3 col-md-2 control-label" style="margin-top: 14px; padding-left: 30px;">Name:</label>
                            <div class="col-xs-9 col-md-10" style="margin-top: 7px;">
                                <%= form.text_field :creator_name, value: @creator_name %>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="form-group">
                            <label class="col-xs-3 col-md-2 control-label" style="margin-top: 14px; padding-left: 30px;">Email:</label>
                            <div class="col-xs-9 col-md-10" style="margin-top: 7px;">
                                <%= form.text_field :creator_email, value: @creator_email %>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="panel panel-default">
            <div class="panel-heading" role="tab" id="headingTwo">
              <h4 class="panel-title">
                <a role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
                  Usage Policy
                </a>
              </h4>
            </div>
            <div id="collapseTwo" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingTwo">
                <div class="panel-body">
                    <div class="alert alert-info">
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                        <%= t('general.init.usage_policy_hint') %>
                    </div>
                    <div class="row">
                        <div class="form-group">
                            <label class="col-xs-3 col-md-2 control-label" style="margin-top: 14px;">Usage Policy:</label>
                            <div class="col-xs-9 col-md-10" style="margin-top: 7px;">
                                <%= form.text_area :usage_policy, rows: 4, style: "width: 100%; font-family: Menlo, Monaco, Consolas, 'Courier New', monospace;", value: @usage_policy %>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>        
        <div class="panel panel-default">
            <div class="panel-heading" role="tab" id="headingThree">
              <h4 class="panel-title">
                <a role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
                  <%= t('general.init.data') %>
                </a>
              </h4>
            </div>
            <div id="collapseThree" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingThree">
                <div class="panel-body">
                    <div class="row" style="margin-bottom: 5px;">
                        <div class="form-group">
                            <label class="col-xs-3 col-md-2 control-label" style="margin-top: 14px;"><%= t('general.init.native_syntax') %>:</label>
                            <div class="col-xs-9 col-md-10" style="margin-top: 7px;">
                                <%= form.collection_select(:data_format,
                                        { t('general.init.native_syntax_none')   => "none",
                                          t('general.init.native_syntax_csv')    => "csv",
                                          t('general.init.native_syntax_json')   => "json",
                                          t('general.init.native_syntax_turtle') => "turtle" }, 
                                        :last, :first, { selected: @data_format_select }, 
                                        multiple: false, id: "data_format-selection" ) %>
                            </div>
                        </div>
                    </div>
                    <div class="row" style="margin-bottom: 15px;">
                        <div class="form-group">
                            <label class="col-xs-3 col-md-2 control-label" style="margin-top: 14px;"><%= t('general.init.data_example') %>:</label>
                            <div class="col-xs-9 col-md-10" style="margin-top: 7px;">
                                <%= form.text_area :data_example, rows: 3, style: "width: 100%" %>
                            </div>
                        </div>
                    </div>

                    <div class="alert alert-info">
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                        <%= t('general.init.data_source_hint') %>
                    </div>
                    <div class="row">
                        <div class="form-group">
                            <label class="col-xs-3 col-md-2 control-label" style="margin-top: 14px;"><%= t('general.init.data_model') %>:</label>
                            <div class="col-xs-9 col-md-10" style="margin-top: 7px;">
                                <%= form.text_area :data_model, rows: 3, style: "width: 100%" %>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="form-group">
                            <label class="col-xs-3 col-md-2 control-label" style="margin-top: 14px;"><%= t('general.init.data_constraints') %>:</label>
                            <div class="col-xs-9 col-md-10" style="margin-top: 7px;">
                                <%= form.text_area :data_constraints, rows: 3, style: "width: 100%" %>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="panel panel-default">
            <div class="panel-heading" role="tab" id="headingFour">
              <h4 class="panel-title">
                <a role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseFour" aria-expanded="false" aria-controls="collapseFour">
                  <%= t('general.validation') %>
                </a>
              </h4>
            </div>
            <div id="collapseFour" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingFour">
                <div class="panel-body">
                    <div class="row">
                        <div class="form-group">
                            <label class="col-xs-3 col-md-2 control-label" style="margin-top: 14px;">Image Constraints:</label>
                            <div class="col-xs-9 col-md-10" style="margin-top: 7px;">
                                <%= form.text_area :image_constraints, rows: 4, style: "width: 100%; font-family: Menlo, Monaco, Consolas, 'Courier New', monospace;", value: @image_constraints %>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>        
    </div>
    <%= form.button value: "create", class: "btn btn-primary", style:"margin-right: 10px;" do %>
        <span class="fa fa-file-text-o" aria-hidden="true"></span>
        <%= t('general.create') %>
    <% end %>
    <%= form.button value: "reset", class: "btn btn-default" do %>
        <span class="glyphicon glyphicon-refresh" aria-hidden="true"></span>
        <%= t('general.reset') %>
    <% end %>
    <p>&nbsp;</p>
    <h4>Container Definition</h4>
    <%= form.hidden_field :init_trig, id: "init_trig" %>
    <div id="editor_create" style="height: 100px; width: 100%; border-radius: 2px; border: 1px solid #DDD; margin-bottom: 15px;"><%= @init_create %></div>

    <% if params[:valid].to_s == "true" %>
        <div class="alert alert-success">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
            <%= t('general.init.validation_success') %>
        </div>
    <% end %>
    <% if params[:valid].to_s == "false" %>
        <div class="alert alert-danger">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
            <%= t('general.init.validation_failure') %>
        </div>
    <% end %>

    <%= form.button value: "validate", class: "btn btn-success", onclick: "$('#init_trig').val(ace.edit('editor_create').getSession().getValue()); return true;" do %>
        <span class="fa fa-check-square-o" aria-hidden="true"></span>
        <%= t('general.validate') %>
    <% end %>
    <button onclick="copyFunction('editor_create'); return false;" onmouseout="outFunc('editor_create')" 
        class="btn btn-default" style="margin-right: 10px;"
        data-toggle="tooltip" data-placement="right" 
        title="<%= t('general.copyClipboard') %>" id="copyButton_editor_create">
        <span class="glyphicon glyphicon-copy" aria-hidden="true"></span>
        <%= t('general.copy') %>
    </button>
    <button class="btn btn-default" onclick="downloadFunction('editor_create', 'init.trig'); return false;">
        <span class="glyphicon glyphicon-download-alt" aria-hidden="true"></span>
        <%= t('general.download') %>
    </button>
<% end %>

<script type="text/javascript">
    var editor = ace.edit("editor_create");
    editor.setOptions({
        showPrintMargin: true,
        maxLines: 15,
        fontSize: "100%"
    });
    editor.setTheme("ace/theme/chrome");
    editor.renderer.setOption("showLineNumbers", true);
</script>

<script type="text/javascript">
    $(document).ready(function() {
        $('#data_format-selection').multiselect({ 
            numberDisplayed: 1 });
        $('#creator_type-selection').multiselect({ 
            numberDisplayed: 1 });
    });
</script>

app/views/pages/_usage_create.html.erb
<%= form_with url: usage_create_submit_path do |form| %>
    <%= form.hidden_field :sidebar, value: params[:sidebar] %>
    <h4><%= t('general.settings') %></h4>
    <div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
        <div class="panel panel-default">
            <div class="panel-heading" role="tab" id="headingOne">
              <h4 class="panel-title">
                <a role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseOne" aria-expanded="false" aria-controls="collapseOne">
                  <%= t('general.usage.options') %>
                </a>
              </h4>
            </div>
            <div id="collapseOne" class="panel-collapse collapse in" role="tabpanel" aria-labelledby="headingOne">
                <div class="panel-body">

                    <p style="color: black;"><%= raw t('general.usage.policy_reference') %></p>

                    <div class="row">
                        <div class="form-group">
                            <label class="col-xs-3 col-md-2 control-label" style="margin-top: 14px;"><%= t('usage.data.label') %>:</label>
                            <div class="col-xs-9 col-md-10" style="margin-top: 7px;">
                                <%= form.collection_select(:data_category, @data_list,
                                        :last, :first, { selected: @data_select }, 
                                        multiple: true, id: "data-selection" ) %>
                            </div>
                        </div>
                    </div>

                    <div class="row">
                        <div class="form-group">
                            <label class="col-xs-3 col-md-2 control-label" style="margin-top: 14px;"><%= t('usage.purpose.label') %>:</label>
                            <div class="col-xs-9 col-md-10" style="margin-top: 7px;">
                                <%= form.collection_select(:purpose, @purpose_list,
                                        :last, :first, { selected: @purpose_select }, 
                                        multiple: true, id: "purpose-selection" ) %>
                            </div>
                        </div>
                    </div>

                    <div class="row">
                        <div class="form-group" style="margin-bottom: 0">
                            <label class="col-xs-3 col-md-2 control-label" style="margin-top: 14px;"><%= t('usage.processing.label') %>:</label>
                            <div class="col-xs-9 col-md-10" style="margin-top: 7px;">
                                <%= form.collection_select(:processing, 
                                        { t('usage.processing.aggregate') => "Aggregate", 
                                          t('usage.processing.analyze')   => "Analyze" ,
                                          t('usage.processing.anonymize') => "Anonymize",
                                          t('usage.processing.collect')   => "Collect",
                                          t('usage.processing.copy')      => "Copy",
                                          t('usage.processing.derive')    => "Derive",
                                          t('usage.processing.move')      => "Move",
                                          t('usage.processing.query')     => "Query",
                                          t('usage.processing.transfer')  => "Transfer" }, 
                                        :last, :first, { selected: @processing_select }, 
                                        multiple: true, id: "processing-selection" ) %>
                            </div>
                            <!-- <div style="white-space: nowrap; display: inline;">
                                <%= form.check_box :check_participants, style: "margin-left: 15px;" %>
                                <label class="control-label" style="margin-top: 14px; margin-left: 5px;"><%= t('general.min_participants') %>:</label>
                                <%= form.number_field :num_participants, class: "form-control",  style: "width: 70px; display: inline; margin-left: 10px;" %>
                            </div> -->
                        </div>
                    </div>

                    <div class="row">
                        <div class="form-group">
                            <label class="col-xs-3 col-md-2 control-label" style="margin-top: 14px;"><%= t('usage.recipient.label') %>:</label>
                            <div class="col-xs-9 col-md-10" style="margin-top: 7px;">
                                <%= form.collection_select(:recipient,
                                        { t('usage.recipient.ours')      => "Ours",
                                          t('usage.recipient.delivery')  => "Delivery",
                                          t('usage.recipient.same')      => "Same",
                                          t('usage.recipient.other')     => "OtherRecipient",
                                          t('usage.recipient.unrelated') => "Unrelated",
                                          t('usage.recipient.public')    => "Public" }, 
                                        :last, :first, { selected: @recipient_select }, 
                                        multiple: true, id: "recipient-selection" ) %>
                            </div>
                        </div>
                    </div>

                    <div class="row">
                        <div class="form-group"">
                            <label class="col-xs-3 col-md-2 control-label" style="margin-top: 14px;"><%= t('usage.location.label') %>:</label>
                            <div class="col-xs-9 col-md-10" style="margin-top: 7px;">
                                <%= form.collection_select(:storage_location, 
                                        { t('usage.location.our_servers')     => "OurServers",
                                          t('usage.location.third_parties')   => "ThirdParty",
                                          t('usage.location.eu')              => "EU" ,
                                          t('usage.location.eu_like')         => "EULike",
                                          t('usage.location.third_countries') => "ThirdCountries" }, 
                                        :last, :first, { selected: @storage_location_select }, 
                                        multiple: true, id: "storage-location-selection" ) %>
                            </div>
                        </div>
                    </div>

                    <div class="row">
                        <div class="form-group">
                            <label class="col-xs-3 col-md-2 control-label" style="margin-top: 14px;"><%= t('usage.duration.label') %>:</label>
                            <div class="col-xs-9 col-md-10" style="margin-top: 7px;">
                                <%= form.collection_select(:storage_duration, 
                                        { t('usage.duration.stated_purpose')     => "StatedPurpose", 
                                          t('usage.duration.legal_requirements')  => "LegalRequirement",
                                          t('usage.duration.business_practices') => "BusinessPractices", 
                                          t('usage.duration.indefinitely')       => "Indefinitely" }, 
                                        :last, :first, { selected: @storage_duration_select }, 
                                        multiple: false, id: "storage-duration-selection" ) %>
                            </div>
                        </div>
                    </div>

                </div>
            </div>
        </div>
    </div>
    <%= form.button value: "create", class: "btn btn-primary", style:"margin-right: 10px;" do %>
        <span class="fa fa-file-text-o" aria-hidden="true"></span>
        <%= t('general.create') %>
    <% end %>
    <%= form.button value: "reset", class: "btn btn-default" do %>
        <span class="glyphicon glyphicon-refresh" aria-hidden="true"></span>
        <%= t('general.reset') %>
    <% end %>
    <p>&nbsp;</p>
    <h4>Usage Policy</h4>
    <%= form.hidden_field :usage_policy, id: "usage_policy" %>
    <div id="editor_create" style="height: 100px; width: 100%; border-radius: 2px; border: 1px solid #DDD; margin-bottom: 15px;"><%= @usage_policy %></div>

    <% if params[:valid].to_s == "true" %>
        <div class="alert alert-success">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
            <%= t('general.usage.validation_success') %>
        </div>
    <% end %>
    <% if params[:valid].to_s == "false" %>
        <div class="alert alert-danger">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
            <%= t('general.usage.validation_failure') %>
        </div>
    <% end %>

    <%= form.button value: "validate", class: "btn btn-success", onclick: "$('#usage_policy').val(ace.edit('editor_create').getSession().getValue()); return true;" do %>
        <span class="fa fa-check-square-o" aria-hidden="true"></span>
        <%= t('general.validate') %>
    <% end %>
    <button onclick="copyFunction('editor_create'); return false;" onmouseout="outFunc()" 
        class="btn btn-default" style="margin-right: 10px;"
        data-toggle="tooltip" data-placement="right" 
        title="<%= t('general.copyClipboard') %>" id="copyButton_editor_create">
        <span class="glyphicon glyphicon-copy" aria-hidden="true"></span>
        <%= t('general.copy') %>
    </button>
    <button class="btn btn-default" onclick="downloadFunction('editor_create', 'usage_policy.trig'); return false;">
        <span class="glyphicon glyphicon-download-alt" aria-hidden="true"></span>
        <%= t('general.download') %>
    </button>
<% end %>

<script type="text/javascript">
    var editor = ace.edit("editor_create");
    editor.setOptions({
        showPrintMargin: true,
        maxLines: 15,
        fontSize: "100%"
    });
    editor.setTheme("ace/theme/chrome");
    editor.renderer.setOption("showLineNumbers", true);
</script>

<script type="text/javascript">
    $(document).ready(function() {
        $('#data-selection').multiselect({ 
            nonSelectedText: '<%= t("general.none_select") %>',
            includeSelectAllOption: true,
            numberDisplayed: 1,
            selectAllText: '<%= t("general.select_all") %>',
            nSelectedText: '<%= t("general.nselect") %>',
            allSelectedText:  '<%= t("general.all_selected") %>'});
        $('#recipient-selection').multiselect({ 
            nonSelectedText: '<%= t("general.none_select") %>',
            includeSelectAllOption: true,
            numberDisplayed: 1,
            selectAllText: '<%= t("general.select_all") %>',
            nSelectedText: '<%= t("general.nselect") %>',
            allSelectedText:  '<%= t("general.all_selected") %>'});
        $('#purpose-selection').multiselect({ 
            nonSelectedText: '<%= t("general.none_select") %>',
            includeSelectAllOption: true,
            numberDisplayed: 1,
            selectAllText: '<%= t("general.select_all") %>',
            nSelectedText: '<%= t("general.nselect") %>',
            allSelectedText:  '<%= t("general.all_selected") %>'});
        $('#processing-selection').multiselect({ 
            nonSelectedText: '<%= t("general.none_select") %>',
            includeSelectAllOption: true,
            numberDisplayed: 1,
            selectAllText: '<%= t("general.select_all") %>',
            nSelectedText: '<%= t("general.nselect") %>',
            allSelectedText:  '<%= t("general.all_selected") %>'});
        $('#storage-location-selection').multiselect({ 
            nonSelectedText: '<%= t("general.none_select") %>',
            includeSelectAllOption: true,
            numberDisplayed: 1,
            selectAllText: '<%= t("general.select_all") %>',
            nSelectedText: '<%= t("general.nselect") %>',
            allSelectedText:  '<%= t("general.all_selected") %>'});
        $('#storage-duration-selection').multiselect({ 
            nonSelectedText: '<%= t("general.none_select") %>',
            includeSelectAllOption: true,
            numberDisplayed: 1,
            selectAllText: '<%= t("general.select_all") %>',
            nSelectedText: '<%= t("general.nselect") %>',
            allSelectedText:  '<%= t("general.all_selected") %>'});
    });
</script>

app/views/pages/_usage_examples.de.html.erb
<h4>Unbeschränkter Zugriff</h4>
<p>Beispiel für eine Nutzungsrichtlinie (Usage Policy) ohne jegliche Beschränkung</p>
<div id="editor_unrestricted" style="height: 100px; width: 100%; border-radius: 2px; border: 1px solid #DDD; margin-bottom: 15px;"><%= File.read("data/usage_policy-unrestricted.trig") %></div>
<button onclick="copyFunction('editor_unrestricted'); return false;" onmouseout="outFunc('editor_unrestricted')" 
    class="btn btn-info" style="margin-right: 10px;"
    data-toggle="tooltip" data-placement="right" 
    title="<%= t('general.copyClipboard') %>" id="copyButton_editor_unrestricted">
    <span class="glyphicon glyphicon-copy" aria-hidden="true"></span>
    <%= t('general.copy') %>
</button>
<button class="btn btn-info" onclick="downloadFunction('editor_unrestricted', 'usage_policy.trig'); return false;">
    <span class="glyphicon glyphicon-download-alt" aria-hidden="true"></span>
    <%= t('general.download') %>
</button>

<script type="text/javascript">
    var editor = ace.edit("editor_unrestricted");
    editor.setOptions({
        showPrintMargin: true,
        maxLines: 10,
        fontSize: "100%"
    });
    editor.setTheme("ace/theme/chrome");
    editor.renderer.setOption("showLineNumbers", true);
</script>